# Generated by Django 2.1.1 on 2018-10-10 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('base_clock', models.FloatField()),
                ('boost_clock', models.FloatField()),
                ('cache_size', models.FloatField()),
                ('no_of_core', models.IntegerField()),
                ('is_HyperThreaded', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('chipset', models.CharField(max_length=200)),
                ('vram_size', models.CharField(max_length=200)),
                ('vram_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LR.CPU')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LR.GPU')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('series', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonal_size', models.FloatField()),
                ('category', models.CharField(max_length=200)),
                ('resolution', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdd_capacity', models.IntegerField()),
                ('ssd_capacity', models.IntegerField()),
                ('ssd_category', models.CharField(max_length=200)),
                ('cache_size', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LR.Screen'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LR.LaptopModel'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LR.RAM'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LR.Storage'),
        ),
    ]
